build:
  version: "1.0"

cards:
  message: "Welcome to spring boot micro-services prod-Api's"
  contactDetails:
    name: "Putul"
    email: "putulkumari0997@gmail.com"
  onCallSupport:
    -(+91) 9999999999
    -(+91) 8888888888